### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by ishepherd** [lmaccherone/documentdb-lumenize#4]
Hi @lmaccherone, this looks promising for a project I'm doing at work.
Has anyone besides you contributed to it? (Seems last commits were in 2015). Are many people using it?
Thanks.
cc @gmar @lizheliu

**Comment by lmaccherone** [comment]
It currently gets 70 downloads a month on npmjs.org. I have been using it constantly since I last published it and I have modified versions of it for various purposes, but I'm the only one who has contributed to it. That said, it's based upon Lumenize which is much more active and has several other significant contributors besides me.

If there is something you want to do with it, I'd be glad to assist.

**Comment by ishepherd** [comment]
Thanks @lmaccherone for quick reply. Glad it is not abandoned :smile:

We had a chat internally, we'll go in a different direction for now. But we'll keep a watch on this project.

Thanks!
